// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXIBYnEcGyPdo0LEGGNHfGYwftDPbeJ2w',
    appId: '1:432754699040:web:8720e1c2c9178cc4e74545',
    messagingSenderId: '432754699040',
    projectId: 'educonnect-dc136',
    authDomain: 'educonnect-dc136.firebaseapp.com',
    storageBucket: 'educonnect-dc136.appspot.com',
    measurementId: 'G-5W6F333N0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLwotGqekGKQ_Kbg5_aosZxznBBcfKM_U',
    appId: '1:432754699040:android:a27f3c0ef96a0493e74545',
    messagingSenderId: '432754699040',
    projectId: 'educonnect-dc136',
    storageBucket: 'educonnect-dc136.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBldSbZVNtvtALv12rnLEvtX8u5_N4_-go',
    appId: '1:432754699040:ios:69c4bee31d548065e74545',
    messagingSenderId: '432754699040',
    projectId: 'educonnect-dc136',
    storageBucket: 'educonnect-dc136.appspot.com',
    iosBundleId: 'com.example.parkjiseongtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBldSbZVNtvtALv12rnLEvtX8u5_N4_-go',
    appId: '1:432754699040:ios:26114b0ee42a693ce74545',
    messagingSenderId: '432754699040',
    projectId: 'educonnect-dc136',
    storageBucket: 'educonnect-dc136.appspot.com',
    iosBundleId: 'com.example.spaghetti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXIBYnEcGyPdo0LEGGNHfGYwftDPbeJ2w',
    appId: '1:432754699040:web:d7654e180a10d192e74545',
    messagingSenderId: '432754699040',
    projectId: 'educonnect-dc136',
    authDomain: 'educonnect-dc136.firebaseapp.com',
    storageBucket: 'educonnect-dc136.appspot.com',
    measurementId: 'G-BT8599FC57',
  );
}
